export const refs = {
  movieCards: document.querySelector('.card-set'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  backdrop: document.querySelector('.js-backdrop'),
  modalBody: document.querySelector('.js-modal__body'),
  modal: document.querySelector('.js-modal'),
  watchedBtn: document.querySelector('.watched-btn'),
  queueBtn: document.querySelector('.queue-btn'),
  searchForm: document.querySelector('.search-form'),
  closeAdvBtn: document.querySelector('.avd__close-btn'),
  advBlock: document.querySelector('.adv'),
  trailerBtn: document.querySelector('.js-trailer'),
  backdropTrailer: document.querySelector('.js-backdrop-trailer'),
  body: document.querySelector('body'),
  spinner: document.querySelector('.js-spinner'),
  load: document.querySelector('[data-load]'),
  openFooterModalBtn: document.querySelector('.footer__btn'),
  closeFooterModalBtn: document.querySelector('.js-close-footer'),
  backdropModalFooter: document.querySelector('.js-backdrop-footer'),
  body: document.querySelector('body'),
  logo: document.querySelector('.header-nav__link'),
};
